apiVersion: v1
kind: Service
metadata:
  name: cpu-monitor-service
spec:
  selector:
    app.kubernetes.io/name: cpu
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80